TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devDMM40X0.db
# FIXME -- HOW TO INSTALL DMM4040.proto????

#=======================================
include $(TOP)/configure/RULES
