TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devDMM40X0.db
DATA += devDMM40X0.proto

#=======================================
include $(TOP)/configure/RULES
